name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      account_number:
        description: 'AWS Account Number'
        required: false
        type: string
      terraform_option:
        description: 'Choose Terraform Option'
        required: true
        type: choice
        default : plan
        options:
          - apply
          - plan
          - destroy
      git_branch:
        description: 'Git Branch to Checkout'
        required: false
        type: string
        default: main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-1' # Replace with your desired AWS region

jobs:
  terraform_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_branch }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Terraform Plan
        if: ${{ github.event.inputs.terraform_option == 'plan' }}
        id: plan
        run: terraform plan -no-color -var-file="config/var.json"
        continue-on-error: true

      - name: Terraform Apply
        if: ${{ github.event.inputs.terraform_option == 'apply' }}
        id: apply
        run: terraform apply -var-file="config/var.json -auto-approve -no-color

      - name: Terraform Destroy
        if: ${{ github.event.inputs.terraform_option == 'destroy' }}
        id: destroy
        run: terraform destroy -auto-approve -no-color

      - name: Output Terraform Plan
        if: steps.plan.outcome == 'failure'
        run: echo "Terraform Plan Failed" && exit 1

      - name: Output Terraform Apply
        if: steps.apply.outcome == 'success'
        run: echo "Terraform Apply Successful"

      - name: Output Terraform Destroy
        if: steps.destroy.outcome == 'success'
        run: echo "Terraform Destroy Successful"
